# Generated by Django 4.0 on 2023-07-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_tasklist_task_list_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='task_list_uuid',
            new_name='list_uuid',
        ),
    ]
