# Generated by Django 4.0 on 2023-07-24 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_rename_task_list_uuid_tasklist_list_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
